import type { ProviderDescriptor } from "./types";

export const providerCatalog: ProviderDescriptor[] = [
  {
    id: "ollama",
    name: "Ollama",
    shortLabel: "OL",
    region: "local",
    adapter: "ollama",
    status: "core",
    description: "Local model runtime. First-class target for Qwen and other model families.",
    defaultBaseUrl: "http://127.0.0.1:11434",
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    shortLabel: "LM",
    region: "local",
    adapter: "openai-compatible",
    status: "core",
    description: "Local model server through its OpenAI-compatible endpoint.",
  },
  {
    id: "llama-cpp",
    name: "llama.cpp server",
    shortLabel: "LC",
    region: "local",
    adapter: "openai-compatible",
    status: "core",
    description: "Local GGUF inference exposed through a compatible server.",
  },
  {
    id: "vllm",
    name: "vLLM",
    shortLabel: "VL",
    region: "local",
    adapter: "openai-compatible",
    status: "core",
    description: "High-throughput local or self-hosted model serving.",
  },
  {
    id: "localai",
    name: "LocalAI",
    shortLabel: "LA",
    region: "local",
    adapter: "openai-compatible",
    status: "core",
    description: "Self-hosted OpenAI-compatible model gateway.",
  },
  {
    id: "custom-local",
    name: "Custom local endpoint",
    shortLabel: "+",
    region: "local",
    adapter: "openai-compatible",
    status: "core",
    description: "Any user-supplied OpenAI-compatible local server.",
  },

  {
    id: "openai",
    name: "OpenAI",
    shortLabel: "OA",
    region: "global",
    adapter: "openai-compatible",
    status: "core",
    description: "OpenAI models through the configurable API adapter.",
    defaultBaseUrl: "https://api.openai.com/v1",
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    shortLabel: "AN",
    region: "global",
    adapter: "anthropic-native",
    status: "cataloged",
    description: "Claude native API adapter for provider-specific features.",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    shortLabel: "GE",
    region: "global",
    adapter: "gemini-native",
    status: "cataloged",
    description: "Gemini native adapter for long-context and multimodal tasks.",
  },
  {
    id: "xai",
    name: "xAI Grok",
    shortLabel: "xAI",
    region: "global",
    adapter: "openai-compatible",
    status: "core",
    description: "Grok through its OpenAI-compatible API surface.",
    defaultBaseUrl: "https://api.x.ai/v1",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    shortLabel: "OR",
    region: "global",
    adapter: "openai-compatible",
    status: "core",
    description: "Multi-provider cloud routing through one compatible endpoint.",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
  },
  {
    id: "mistral",
    name: "Mistral",
    shortLabel: "MI",
    region: "global",
    adapter: "openai-compatible",
    status: "core",
    description: "Mistral cloud models through the shared compatible adapter.",
  },
  {
    id: "custom-cloud",
    name: "Custom cloud endpoint",
    shortLabel: "+",
    region: "global",
    adapter: "openai-compatible",
    status: "core",
    description: "Any user-supplied OpenAI-compatible cloud endpoint.",
  },

  {
    id: "qwen-cloud",
    name: "Alibaba Qwen / Model Studio",
    shortLabel: "QW",
    region: "china",
    adapter: "openai-compatible",
    status: "core",
    description: "Qwen cloud models through a configurable compatible endpoint.",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    shortLabel: "DS",
    region: "china",
    adapter: "openai-compatible",
    status: "core",
    description: "DeepSeek models through the shared compatible adapter.",
  },
  {
    id: "kimi",
    name: "Moonshot / Kimi",
    shortLabel: "KM",
    region: "china",
    adapter: "openai-compatible",
    status: "core",
    description: "Kimi models through a configurable compatible endpoint.",
  },
  {
    id: "glm",
    name: "Zhipu / GLM",
    shortLabel: "GL",
    region: "china",
    adapter: "openai-compatible",
    status: "core",
    description: "GLM models through a configurable compatible endpoint.",
  },
  {
    id: "minimax",
    name: "MiniMax",
    shortLabel: "MM",
    region: "china",
    adapter: "openai-compatible",
    status: "core",
    description: "MiniMax models through a configurable compatible endpoint.",
  },
  {
    id: "doubao",
    name: "ByteDance / Doubao",
    shortLabel: "DB",
    region: "china",
    adapter: "openai-compatible",
    status: "core",
    description: "Doubao/Ark models through a configurable compatible endpoint.",
  },
  {
    id: "ernie",
    name: "Baidu ERNIE / Qianfan",
    shortLabel: "ER",
    region: "china",
    adapter: "custom",
    status: "cataloged",
    description: "Baidu cloud models behind a provider-specific adapter.",
  },
  {
    id: "hunyuan",
    name: "Tencent Hunyuan",
    shortLabel: "HY",
    region: "china",
    adapter: "custom",
    status: "cataloged",
    description: "Tencent cloud models behind a provider-specific adapter.",
  },
];
